# Generated by Django 5.1.5 on 2025-04-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0002_alter_user_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('pancard_no', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('license', models.CharField(blank=True, max_length=11, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent', to='administrator.user')),
            ],
        ),
    ]
