# Generated by Django 5.1.5 on 2025-02-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.CharField(default='okg', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='weight',
            field=models.CharField(max_length=20),
        ),
    ]
