# Generated by Django 5.1.5 on 2025-02-20 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('customer', '0004_remove_order_buyer_remove_order_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordercart',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=1, limit_choices_to={'rights': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_buyer', to='administrator.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking')], default='cod', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=0, limit_choices_to={'rights': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_seller', to='administrator.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Ordercart',
        ),
    ]
