# Generated by Django 5.1.5 on 2025-04-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_cart_price_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
