# Generated by Django 5.1.5 on 2025-04-13 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_message_options_remove_message_message_and_more'),
        ('customer', '0007_cart_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'rights': 'delivery'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_delivery_user', to='administrator.user'),
        ),
    ]
