# Generated by Django 5.1.5 on 2025-02-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'rights': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='administrator.user'),
        ),
    ]
