# Generated by Django 5.1.5 on 2025-02-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_price_weight_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='weight',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
