# Generated by Django 5.1.5 on 2025-02-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_is_veg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='weight',
            field=models.CharField(max_length=20),
        ),
    ]
