# Generated by Django 5.1.5 on 2025-04-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_sellerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetails',
            name='Address',
            field=models.TextField(default='address'),
            preserve_default=False,
        ),
    ]
