# Generated by Django 5.1.5 on 2025-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rights',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('customer', 'Customer'), ('delivery', 'Delivery')], default='customer', max_length=50),
        ),
    ]
